checks:
    php: true

filter:
    excluded_paths:
        - tests/*

build:
    environment:
        php: '5.6'

    tests:
        override:
            -
                command: 'phpunit --coverage-clover=clover.txt'
                coverage:
                    file: 'clover.txt'
                    format: 'php-clover'